---
- name: "Check if {{ samba_user.name }} already has a Samba password"
  ansible.builtin.command: pdbedit -L -u {{ samba_user.name }}
  register: samba_user_check
  changed_when: false
  failed_when: false

- name: "Prompt for {{ samba_user.name }}'s Samba password"
  ansible.builtin.pause:
    prompt: "Enter Samba password for user '{{ samba_user.name }}' (input hidden, press enter when done)"
    echo: false
  register: samba_password_prompt
  when: samba_user_check.rc != 0
  no_log: true

- name: "Set Samba password for {{ samba_user.name }}"
  ansible.builtin.shell: |
    (echo "{{ samba_password_prompt.user_input }}"; echo "{{ samba_password_prompt.user_input }}") | smbpasswd -a -s {{ samba_user.name }}
  when: samba_user_check.rc != 0
  no_log: true
  changed_when: true
