---
- name: reboot pi
  ansible.builtin.reboot:
    reboot_timeout: 300
    msg: "Rebooting to apply boot config.txt changes (PCIe settings)"

- name: restart wol service
  ansible.builtin.systemd:
    name: wol
    state: restarted
    daemon_reload: true
